data:
  custom_loader_method: steps.ingest.load_file_as_dataframe
  format: parquet
  location: ./data/sample.parquet
data_scoring:
  custom_loader_method: steps.ingest.load_file_as_dataframe
  format: parquet
  location: ./data/sample.parquet
  sql: SELECT * FROM delta.`./data/sample.parquet`
experiment:
  artifact_location: ./metadata/mlflow/mlartifacts
  name: sklearn_regression_experiment
  tracking_uri: sqlite:///metadata/mlflow/mlruns.db
steps:
  evaluate:
    metrics:
      custom:
      - function: steps.metrics.weighted_mean_squared_error
        greater_is_better: false
        name: weighted_mean_squared_error
      primary: root_mean_squared_error
    validation_criteria:
    - metric: root_mean_squared_error
      threshold: 100
    - metric: mean_absolute_error
      threshold: 500
    - metric: weighted_mean_squared_error
      threshold: 200
  predict:
    output_format: parquet
    output_location: ./data/sample_output.parquet
  register:
    allow_non_validated_model: false
    model_name: mymodel
  split:
    split_ratios:
    - 0.1
    - 0.1
    - 0.8
  train:
    estimator_method: steps.train.estimator_fn
    metrics:
      custom:
      - function: steps.metrics.weighted_mean_squared_error
        greater_is_better: true
        name: weighted_mean_squared_error
      primary: root_mean_squared_error
  transform:
    transformer_method: steps.transform.transformer_fn
  transformer_method: steps.transform.transformer_fn
target_col: fare_amount
template: regression/v1
